theme: mmibordeaux-hugo-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: content
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"